### ISSUE TITLE
Idea: Build an MPI test suite against the installed stubs library in CI

### ISSUE THREAD

**Issue by eschnett** [mpiwg-abi/header_and_stub_library#16]

**Comment by jeffhammond** [comment]
MPICH test suite should be ABI agnostic now. We can use that.

**Comment by dalcinl** [comment]
Building mp4py would also be good. I don't think many testsuites out there cover all the large count APIs.

**Comment by jeffhammond** [comment]
a very quick `sed` operation on https://github.com/jeffhammond/BigMPI/tree/master/test should generate some large-count tests.

does MPICH not test large count APIs?  that is surprising.

**Comment by hzhou** [comment]
We test the usage of large-count APIs. But the real test is to test counts that are larger than INT_MAX, which is some kind of stress testing. We only have a couple of simple tests that do that in regular CI testing, unfortunately. Thus the coverage is low.

**Comment by jeffhammond** [comment]
That isn't relevant here, is it? We are only compiling and linking to see the symbols exist, right?

**Comment by dalcinl** [comment]
See #17.

**Comment by dalcinl** [comment]
@eschnett Are the mpi4py workflow I've added enough for your intentions? I believe the only thing mpi4py does not cover are the `MPI_F08_status` APIs, other than that, I think everything in MPI 4.1 is used. I may be missing something, though.
