### ISSUE TITLE
MPI_SIZEOF is Fortran-only

### ISSUE THREAD

**Issue by dalcinl** [mpiwg-abi/header_and_stub_library#4]
From MPI 4.1 pp 777

_Rationale_. This function is not available in other languages because it would not be useful. (End of rationale.)

Should we remove it from the `mpi.h` header here? Or maybe comment it out with a note that it is Fortran-only?

**Comment by jeffhammond** [comment]
We deprecated it already so I'm not sure it even matters.

**Comment by dalcinl** [comment]
I'll submit a PR with the removal.
